### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by bartosz-skejcik** [UdaraJay/Pile#99]
## Summary

I'm wondering if there is gonna be a linux support for this app.

**Comment by UdaraJay** [comment]
hopefully in v1; I haven't had the time to check on linux yet, but if someone can take a look and fix the build issues for linux I'd be happy to publish it!

**Comment by bartosz-skejcik** [comment]
@adityakrcodes I mean i could at least try. not sure if I'll be useful in any way. I would have to get familiar with the codebase.

**Comment by gregorylearns** [comment]
> > hopefully in v1; I haven't had the time to check on linux yet, but if someone can take a look and fix the build issues for linux I'd be happy to publish it!
> 
> I tested it on my Arch machine. It worked fine. I'm still going to test it thoroughly and will update it here. [@bartosz-skejcik](https://github.com/bartosz-skejcik) , wanna collab on building it for Linux?

Hi @adityakrcodes  would you mind sharing your build instructions? I've been having trouble in running it due to an error in the safeStorage module. The following is my error when running the AppImage or the compiled app

```
 JavaScript error occurred in the main process
Uncaught Exception:
Error: Encryption is not available on this system.
    at 12204 (/tmp/.mount_Pile-1wMkmKG/resources/app.asar/dist/main/main.js:2:318237)
    at __webpack_require__ (/tmp/.mount_Pile-1wMkmKG/resources/app.asar/dist/main/main.js:2:1948106)
    at /tmp/.mount_Pile-1wMkmKG/resources/app.asar/dist/main/main.js:2:1951978
    at /tmp/.mount_Pile-1wMkmKG/resources/app.asar/dist/main/main.js:2:1960202
    at /tmp/.mount_Pile-1wMkmKG/resources/app.asar/dist/main/main.js:2:1960226
    at /tmp/.mount_Pile-1wMkmKG/resources/app.asar/dist/main/main.js:2:84
    at Object.<anonymous> (/tmp/.mount_Pile-1wMkmKG/resources/app.asar/dist/main/main.js:2:223)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
```

my `main.js` has the following line
```
s = n(84157); if (!s.safeStorage.isEncryptionAvailable()) throw new Error("Encryption is not available on this system.");
```

the difference in how it works on linux is briefly mentioned [here](https://github.com/electron/electron/issues/33640).

Thanks for your help!
